---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

images:
  base_image:
    name: ghcr.io/ansible/community-ansible-dev-tools:v24.12.0
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: ansible.aws
      - name: ansible.network
      - name: community.vmware
      - name: ansible.windows
      - name: redhatinsights.insights
  system:
    - net-tools
    - curl
  python:
    - pandas
options:
  tags:
    - latest
