---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

images:
  base_image:
    name: ghcr.io/ansible/community-ansible-dev-tools:v24.12.0
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
    # todo - set the source url for internally hosted collections to get access to non community collections
      - name: amazon.aws 
      - name: ansible.netcommon
      - name: ansible.posix
      - name: ansible.builtin
      - name: community.vmware
      - name: community.zabbix
      - name: community.windows
      # - name: redhatinsights.insights
  system:
    - net-tools
    - curl
  python:
    - pandas
options:
  tags:
    - latest
