---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre --ignore-certs'
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: ' --ignore-certs'

images:
  base_image:
    # name: ghcr.io/ansible/community-ansible-dev-tools:v24.12.0
    # name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest

additional_build_steps:
  prepend_base:
    - RUN echo "hello world 🗺️"
    # example for private nexus repo for pypy
    # - RUN $PYCMD -m pip config set global.index-url https://nexus.internal/repository/pypi-group/simple
    # - RUN $PYCMD -m pip config set global.trusted-host nexus.internal
    - RUN $PYCMD -m pip config list
  prepend_galaxy:
    - RUN echo "hello galaxy 🌌"
    # todo might need something like this for custom repos for galaxy 
    # - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
    # todo - set the source url for internally hosted collections to get access to non community collections
      - name: amazon.aws 
      - name: ansible.netcommon
      # - name: ansible.posix
      # # - name: ansible.builtins
      # - name: community.vmware
      # - name: community.zabbix
      - name: community.windows
      # - name: redhatinsights.insights
  system:
    - net-tools
  python:
    - pandas

options:
  package_manager_path: /usr/bin/microdnf # needed for rhel images
  # tags:
  #   - latest
