---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ansible-ee-pipeline
spec:
  workspaces:
    - name: shared-workspace
      description: Workspace for source code and build artifacts
  params:
    - name: git-url
      description: Git repository URL to clone
      type: string
      default: "https://github.com/springdo/ansible-execution-env.git"
    - name: git-revision
      description: Git revision to checkout (branch, tag, sha, ref…)
      type: string
      default: "main"
    - name: ee-dir
      description: Directory containing the execution environment definition
      type: string
      default: "example"
    - name: ee-config
      description: Name of the execution environment definition file
      type: string
      default: "execution-environment.yml"
    - name: image-tag
      description: Tag of the image to build
      type: string
      default: "latest"
    - name: registry
      description: Registry to push the image to
      type: string
      default: "aap-hub.internal"
    - name: image-namespace
      description: Namespace in the registry to push the image to
      type: string
      default: "ee-auto-test"
    - name: is-dev-build
      description: If true, build for internal use. If false, push to external registry
      type: string
      default: "false"
    - name: hub-push-secret
      description: Name of the secret for pushing to the registry
      type: string
      default: "hub-push-secret"
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    - name: validate-and-create
      taskRef:
        name: validate-and-create-ee
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: ee-dir
          value: $(params.ee-dir)
        - name: ee-config
          value: $(params.ee-config)
    
    - name: build-and-push
      taskRef:
        name: build-and-push-ee
      runAfter:
        - validate-and-create
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: $(params.ee-dir)
        - name: image-tag
          value: $(params.image-tag)
        - name: registry
          value: $(params.registry)
        - name: image-namespace
          value: $(params.image-namespace)
        - name: is-dev-build
          value: $(params.is-dev-build)
        - name: hub-push-secret
          value: $(params.hub-push-secret)
        - name: ee-dir
          value: $(params.ee-dir)
