---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ansible-ee-pipeline-trigger-binding
spec:
  params:
    - name: git-url
      value: $(body.project.git_http_url)
    - name: git-repo-name
      value: $(extensions.git-repo-name)
    - name: ee-dir
      value: $(extensions.ee-dir)
    - name: git-revision
      value: $(extensions.truncated-sha)
    - name: git-user-id
      value: $(extensions.git-user-id) 
    - name: git-user-mail
      value: $(extensions.git-user-mail)
    - name: git-commit-msg
      value: $(extensions.git-commit-msg)

